name: build-test
on:
  push:
    branches:
      - 'main'
      - 'release-**'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # pin@v4.1.1
      - name: Setup Go
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # pin@4.1.0
        with:
          go-version: '1.20'
      - name: Install golangci-lint
        run: sudo go install github.com/golangci/golangci-lint/cmd/golangci-lint@v${GOLANGCI_LINT_VERSION}
        env:
          GOBIN: '/usr/local/bin'
          GOLANGCI_LINT_VERSION: '1.55.2'
      - name: Test style
        run: make test-style
      - name: Run unit tests
        run: make test-coverage
      - name: Test build
        run: make build
